In [95]:
import pandas as pd
import numpy as np

In [61]:
interactions = pd.read_csv("interactions.csv", sep='\t')
items = pd.read_csv("items.csv", sep='\t')
users = pd.read_csv("users.csv", sep='\t')

#### Check columns and rename them

In [62]:
users.columns.tolist()

['recsyschallenge_v2017_users_final_anonym_export_unique.id',
 'recsyschallenge_v2017_users_final_anonym_export_unique.jobroles',
 'recsyschallenge_v2017_users_final_anonym_export_unique.career_level',
 'recsyschallenge_v2017_users_final_anonym_export_unique.discipline_id',
 'recsyschallenge_v2017_users_final_anonym_export_unique.industry_id',
 'recsyschallenge_v2017_users_final_anonym_export_unique.country',
 'recsyschallenge_v2017_users_final_anonym_export_unique.region',
 'recsyschallenge_v2017_users_final_anonym_export_unique.experience_n_entries_class',
 'recsyschallenge_v2017_users_final_anonym_export_unique.experience_years_experience',
 'recsyschallenge_v2017_users_final_anonym_export_unique.experience_years_in_current',
 'recsyschallenge_v2017_users_final_anonym_export_unique.edu_degree',
 'recsyschallenge_v2017_users_final_anonym_export_unique.edu_fieldofstudies',
 'recsyschallenge_v2017_users_final_anonym_export_unique.wtcj',
 'recsyschallenge_v2017_users_final_anonym_export_unique.premium']

In [63]:
users = users.rename(axis='columns', mapper={
    'recsyschallenge_v2017_users_final_anonym_export_unique.id': 'id',
    'recsyschallenge_v2017_users_final_anonym_export_unique.jobroles':'job_roles',
    'recsyschallenge_v2017_users_final_anonym_export_unique.career_level':'career_level', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.discipline_id':'discipline_id', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.industry_id':'industry_id', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.country':'country', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.region':'region', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.experience_n_entries_class':'experience_n_entries_class', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.experience_years_experience':'experience_years_experience', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.experience_years_in_current':'experience_years_in_current',
    'recsyschallenge_v2017_users_final_anonym_export_unique.edu_degree':'edu_degree', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.edu_fieldofstudies':'edu_fieldofstudies', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.wtcj':'wtcj', 
    'recsyschallenge_v2017_users_final_anonym_export_unique.premium':'premium'})

In [64]:
items.columns.tolist()

['recsyschallenge_v2017_items_final_training_export.id',
 'recsyschallenge_v2017_items_final_training_export.title',
 'recsyschallenge_v2017_items_final_training_export.career_level',
 'recsyschallenge_v2017_items_final_training_export.discipline_id',
 'recsyschallenge_v2017_items_final_training_export.industry_id',
 'recsyschallenge_v2017_items_final_training_export.country',
 'recsyschallenge_v2017_items_final_training_export.is_payed',
 'recsyschallenge_v2017_items_final_training_export.region',
 'recsyschallenge_v2017_items_final_training_export.latitude',
 'recsyschallenge_v2017_items_final_training_export.longitude',
 'recsyschallenge_v2017_items_final_training_export.employment',
 'recsyschallenge_v2017_items_final_training_export.tags',
 'recsyschallenge_v2017_items_final_training_export.created_at']

In [65]:
items = items.rename(axis='columns', mapper={
 'recsyschallenge_v2017_items_final_training_export.id':'id',
 'recsyschallenge_v2017_items_final_training_export.title':'title',
 'recsyschallenge_v2017_items_final_training_export.career_level':'career_level',
 'recsyschallenge_v2017_items_final_training_export.discipline_id':"discipline_id",
 'recsyschallenge_v2017_items_final_training_export.industry_id':"industry_id",
 'recsyschallenge_v2017_items_final_training_export.country':'country',
 'recsyschallenge_v2017_items_final_training_export.is_payed':'is_payed',
 'recsyschallenge_v2017_items_final_training_export.region':'region',
 'recsyschallenge_v2017_items_final_training_export.latitude':'latitude',
 'recsyschallenge_v2017_items_final_training_export.longitude':'longitude',
 'recsyschallenge_v2017_items_final_training_export.employment':'employment',
 'recsyschallenge_v2017_items_final_training_export.tags':'tags',
 'recsyschallenge_v2017_items_final_training_export.created_at':'created_at'
})

In [66]:
interactions.columns.to_list()

['recsyschallenge_v2017_interactions_final_anonym_training_export.user_id',
 'recsyschallenge_v2017_interactions_final_anonym_training_export.item_id',
 'recsyschallenge_v2017_interactions_final_anonym_training_export.interaction_type',
 'recsyschallenge_v2017_interactions_final_anonym_training_export.created_at']

In [67]:
interactions = interactions.rename(axis='columns', mapper={
 'recsyschallenge_v2017_interactions_final_anonym_training_export.user_id':'user_id',
 'recsyschallenge_v2017_interactions_final_anonym_training_export.item_id':'item_id',
 'recsyschallenge_v2017_interactions_final_anonym_training_export.interaction_type':'interaction_type',
 'recsyschallenge_v2017_interactions_final_anonym_training_export.created_at':'created_at'
})

In [68]:
interactions['created_at']

0            1484299172
1            1486388563
2            1479409825
3            1484817366
4            1486370081
                ...
322775997    1485433078
322775998    1485432992
322775999    1485256322
322776000    1485433139
322776001    1485422407
Name: created_at, Length: 322776002, dtype: int64

#### Preprocess the interactions

In [69]:
# only keep positive interactions
interactions = interactions[interactions['interaction_type'].isin([1,2,3,5])]

In [70]:
# sort by time
interactions.sort_values(by='created_at', inplace=True)

In [71]:
# convert timestamps to dates
interactions['date'] = pd.to_datetime(interactions['created_at'], unit='s')
max_date = interactions['date'].max() # find the latest timestamp
cutoff = max_date - pd.Timedelta(days=7) # define a cutoff of exactly one week

In [72]:
before_cutoff = interactions[interactions["date"] <= cutoff]
after_cutoff = interactions[interactions["date"] > cutoff] # last week

In [73]:
# now we need to filter the users such that they will have interactions both before and after the one week cutoff
# because we will take the target item from after the cutoff, but the history will be based on interactions before the cutoff
before_counts = before_cutoff.groupby('user_id').size()
after_counts = after_cutoff.groupby('user_id').size()

valid_users = before_counts[before_counts >= 3].index
valid_users = valid_users.intersection(after_counts[after_counts >= 1].index)

before_cutoff = before_cutoff[before_cutoff['user_id'].isin(valid_users)]
after_cutoff = after_cutoff[after_cutoff['user_id'].isin(valid_users)]
users = users[users['id'].isin(valid_users)]

In [74]:
# check the total number of users now
len(users)

94571

#### Construct the user history

In [75]:
# build the user history by taking last 10 interactions before the cutoff
K = 10
history_dict = {}

for user in valid_users:
    user_hist = before_cutoff[before_cutoff['user_id'] == user]
    
    # already sorted ascending, take last K
    last_k_items = user_hist['item_id'].tolist()[-K:]
    
    history_dict[user] = last_k_items

In [76]:
history_dict

{13: [911571,
  2180558,
  29515,
  935433,
  29515,
  29515,
  935433,
  961206,
  79469,
  1094586],
 19: [890853, 890853, 1916214, 1056811, 1916214],
 68: [997637, 517262, 436603, 1006276, 997637],
 169: [294125,
  1983375,
  1164758,
  294125,
  758659,
  1079747,
  1056733,
  1451437,
  1813222,
  1325373],
 217: [951234,
  1219316,
  1969265,
  1969265,
  1969265,
  1969265,
  1969265,
  1969265,
  1969265,
  1969265],
 219: [184181, 1728894, 1728894, 1728894, 944235],
 247: [959920,
  2080651,
  2210601,
  1319364,
  1048507,
  879873,
  346836,
  1785953,
  2210601,
  1636026],
 280: [1602601, 957408, 675177, 1710195, 2192319],
 320: [655090,
  633644,
  530179,
  1898096,
  349311,
  633644,
  1349108,
  193982,
  795594,
  1207436],
 338: [680697,
  1569109,
  938617,
  1092146,
  2177474,
  43637,
  1569109,
  620291,
  1579534,
  740021],
 407: [276797,
  1726165,
  1018637,
  1936784,
  1936784,
  1726165,
  547328,
  1700355,
  1495339,
  1495339],
 423: [203667,
  494772,
  1135138,
  1135138,
  2195784,
  2195784,
  2195784,
  2195784,
  994082,
  994082],
 440: [634697,
  634697,
  1803498,
  2121142,
  2121142,
  634697,
  634697,
  634697,
  583623,
  1403937],
 534: [1367703,
  917291,
  163709,
  1565668,
  194725,
  1935328,
  1935328,
  605341,
  588308,
  588308],
 540: [811645,
  604492,
  1000843,
  1000843,
  1000843,
  1000843,
  1000843,
  915501,
  1250517,
  1054339],
 544: [788697,
  833808,
  1401251,
  408189,
  1385915,
  111278,
  1888384,
  936300,
  2199984,
  88824],
 561: [830076,
  1968818,
  1819476,
  2098399,
  2173089,
  2277525,
  1755605,
  1847110,
  939916,
  1337440],
 599: [969422,
  2242802,
  559785,
  1222043,
  1222043,
  1671095,
  402657,
  402657,
  1208320,
  1208320],
 647: [1818138,
  1380066,
  1475714,
  341804,
  1549484,
  1549484,
  543815,
  1961854,
  1404440,
  1818138],
 672: [1612756,
  750581,
  692555,
  1668817,
  594918,
  2062808,
  748265,
  2274187,
  482302,
  153599],
 693: [225939, 71934, 225939, 593717, 2282518, 2282518, 2280599],
 730: [382493, 2110881, 1350099, 1393033, 1502036, 142531, 346927, 1522939],
 744: [634697,
  2121142,
  2121142,
  1803498,
  634697,
  634697,
  583623,
  1403937,
  722448,
  722448],
 751: [634697,
  634697,
  2121142,
  2121142,
  1803498,
  634697,
  634697,
  634697,
  583623,
  1403937],
 757: [634697,
  634697,
  2121142,
  2121142,
  1803498,
  634697,
  634697,
  634697,
  583623,
  1403937],
 798: [634697,
  634697,
  1803498,
  2121142,
  2121142,
  634697,
  634697,
  634697,
  583623,
  1403937],
 822: [78742,
  1176348,
  1913566,
  576816,
  576816,
  576816,
  1183633,
  2005146,
  2202388,
  1957101],
 824: [1714698, 1512993, 822803, 2200205, 487489, 40541, 1343627, 864714],
 844: [1354031, 2133337, 1891286, 1751605, 1025547, 1224840],
 852: [904681,
  1184568,
  622321,
  732142,
  1923463,
  1400773,
  1445747,
  1665176,
  1867245,
  91074],
 855: [1161839,
  915606,
  606420,
  523596,
  1589545,
  1972175,
  1972175,
  476255,
  2105666,
  2107770],
 892: [1347528, 2088253, 774047, 2167227, 2167227, 2106208, 1186579, 1186579],
 898: [533293, 1239779, 1753637, 1142355, 900241],
 909: [1146371,
  1359863,
  719960,
  543815,
  1961854,
  1813172,
  1009015,
  105468,
  1961854,
  437748],
 936: [972707,
  890062,
  2046635,
  2046635,
  1073927,
  1073927,
  517172,
  1377392,
  1377392,
  1027230],
 989: [833200, 113505, 931891, 62973],
 997: [1640537,
  291132,
  1433023,
  1839947,
  371843,
  945708,
  1729257,
  1810959,
  2190292,
  1467336],
 998: [2120010,
  1933133,
  1522379,
  2211666,
  987910,
  2211666,
  1236170,
  219540,
  1457657,
  2196477],
 1006: [1090409,
  930653,
  98031,
  1602883,
  2206355,
  2199554,
  763522,
  1814215,
  1666859,
  1251308],
 1013: [634697,
  634697,
  2121142,
  1803498,
  2121142,
  634697,
  634697,
  634697,
  583623,
  1403937],
 1034: [2041051,
  74905,
  276679,
  2093788,
  74905,
  276679,
  276679,
  276679,
  2041051,
  1035849],
 1052: [1027244,
  1705312,
  1130834,
  727552,
  1844215,
  944985,
  15672,
  1557163,
  1148133,
  1651308],
 1083: [686840, 942974, 1875774, 1144673],
 1120: [634697,
  634697,
  634697,
  634697,
  2121142,
  2121142,
  634697,
  634697,
  583623,
  1403937],
 1125: [2096789,
  1178767,
  1143278,
  902062,
  2247974,
  1156647,
  1156647,
  1392434,
  1156647,
  2134112],
 1141: [1108545,
  1108545,
  1763856,
  1763856,
  388081,
  388081,
  1253710,
  1591071,
  1443230,
  1629563],
 1145: [1974335, 996827, 2038782, 1228760],
 1241: [634697,
  634697,
  2121142,
  2121142,
  1803498,
  634697,
  634697,
  634697,
  583623,
  1403937],
 1252: [2015132,
  1927553,
  753941,
  473905,
  2072450,
  611803,
  23088,
  1991262,
  951053,
  951053],
 1253: [755366,
  342086,
  1482559,
  1675517,
  2208266,
  469777,
  1792707,
  172515,
  8480,
  1518434],
 1302: [1923463,
  2105961,
  904681,
  13510,
  622321,
  1400773,
  1884613,
  1445747,
  1665176,
  1867245],
 1326: [1565517, 970660, 970660, 257570, 1069210, 1069210, 27374],
 1366: [1526245,
  1578800,
  1120973,
  640109,
  1122421,
  1511455,
  760007,
  374156,
  374156,
  1070671],
 1373: [771160,
  771160,
  771160,
  771160,
  1533664,
  686840,
  1425022,
  1425022,
  439201,
  439201],
 1391: [437838,
  313045,
  2028074,
  17757,
  374156,
  244857,
  706358,
  1581247,
  1101050,
  1811536],
 1442: [2093788,
  74905,
  74905,
  2041051,
  276679,
  276679,
  2041051,
  276679,
  197017,
  1035849],
 1454: [2121142,
  2121142,
  1803498,
  634697,
  634697,
  634697,
  583623,
  1403937,
  722448,
  722448],
 1482: [537712,
  537712,
  1670426,
  1758530,
  837778,
  762310,
  579012,
  488881,
  1018195,
  1018195],
 1532: [634697,
  634697,
  634697,
  634697,
  2121142,
  2121142,
  634697,
  634697,
  583623,
  1403937],
 1574: [634697,
  634697,
  634697,
  634697,
  2121142,
  634697,
  634697,
  634697,
  583623,
  1403937],
 1575: [879873,
  346836,
  1319364,
  2210601,
  2210601,
  160373,
  1636026,
  863468,
  1785953,
  959920],
 1588: [1865937, 384610, 2159978, 967126, 384610, 1743254],
 1604: [424105, 424105, 2181093, 1461248, 777903],
 1658: [1803498,
  2121142,
  2121142,
  634697,
  634697,
  634697,
  583623,
  1403937,
  722448,
  722448],
 1664: [1337442,
  1321067,
  1656904,
  468137,
  468137,
  853637,
  1480108,
  2065467,
  703943,
  795985],
 1704: [504915,
  554007,
  739896,
  739896,
  536468,
  162887,
  124228,
  363195,
  739896,
  739896],
 1753: [1481174,
  1481174,
  75156,
  75156,
  75156,
  75156,
  75156,
  75156,
  1867816,
  1845340],
 1763: [703488, 1352700, 1352700, 1352700, 1352700, 1449960, 1352700],
 1816: [815202,
  1976902,
  1307806,
  1742949,
  711410,
  735060,
  1862898,
  752833,
  1119475,
  127997],
 1821: [2142931,
  420051,
  1963515,
  1648065,
  915771,
  1728282,
  1817932,
  700868,
  758981,
  1916217],
 1833: [101236, 101236, 942382, 1603179, 415585, 1516107, 1242379],
 1843: [641744,
  1578273,
  1578273,
  1847749,
  1847749,
  1244568,
  141366,
  1831433,
  1152484,
  1372886],
 1847: [1706818,
  1599147,
  1349108,
  1018543,
  1528062,
  2242366,
  2242366,
  478203,
  1153069],
 1868: [1730883,
  2122236,
  1539553,
  2089859,
  208971,
  2224503,
  373388,
  951397,
  1809044,
  111999],
 1883: [622321,
  2105961,
  1923463,
  904681,
  1184568,
  13510,
  1884613,
  1445747,
  1665176,
  1867245],
 1895: [184181, 1728894, 1728894, 944235],
 1910: [1556546,
  1343756,
  1831377,
  558019,
  2279057,
  1444229,
  1853436,
  2054691,
  1343756,
  1619372],
 1912: [957420,
  1435723,
  709162,
  1038783,
  150935,
  183922,
  1458997,
  1146974,
  1512683,
  1380832],
 1918: [271882,
  660134,
  901412,
  1956741,
  1956741,
  2188190,
  2188190,
  1358768,
  1431687,
  1049531],
 1919: [1376529,
  567641,
  13706,
  895782,
  1116486,
  567641,
  1376529,
  1488700,
  54815,
  54815],
 1928: [980256, 288684, 200575],
 1958: [1558428, 1689397, 1653628],
 1966: [771160,
  771160,
  771160,
  771160,
  1533664,
  686840,
  1425022,
  1425022,
  439201,
  439201],
 1974: [142305, 1298556, 1270996, 2008765, 2207751],
 1984: [2121142,
  2121142,
  1803498,
  634697,
  634697,
  634697,
  583623,
  1403937,
  722448,
  722448],
 1990: [2243930, 2243930, 2243930, 1707526, 43708, 1707526],
 2075: [2079867, 2162556, 2162556],
 2108: [1528790,
  880152,
  127146,
  1962433,
  1962433,
  1511247,
  1511247,
  1899641,
  851160,
  851160],
 2149: [399783, 681103, 399783, 742134, 1747638, 492884],
 2150: [1958026,
  1958026,
  2034878,
  1868829,
  1933755,
  1933755,
  1409381,
  1053631,
  184151,
  184151],
 2182: [1514471,
  2257343,
  1329333,
  888058,
  1329333,
  1729440,
  779684,
  1729440,
  532118,
  1250359],
 2205: [634697,
  634697,
  634697,
  2121142,
  1803498,
  2121142,
  634697,
  634697,
  634697,
  1403937],
 2224: [980773, 1711553, 1706612],
 2263: [1016174, 1467336, 828565],
 2268: [763889,
  691577,
  171475,
  766156,
  763889,
  2268742,
  1609700,
  1965405,
  1606632,
  1785549],
 2286: [2204486, 1196245, 1449093],
 2299: [569090,
  1154488,
  323605,
  2253234,
  2153893,
  2262649,
  1282812,
  1962537,
  1185512,
  443310],
 2319: [1963169, 2104672, 1382613, 705588, 1720044, 84887, 84887, 84887],
 2350: [437183,
  525366,
  808553,
  1469305,
  1553120,
  351228,
  2274703,
  1745151,
  1104914,
  1926995],
 2375: [2278300,
  229489,
  93386,
  2091816,
  1716321,
  2011252,
  2190847,
  925224,
  550090,
  550090],
 2387: [1749227, 13176, 13176, 1543217],
 2400: [980256, 288684, 200575],
 2438: [634697,
  634697,
  2121142,
  1803498,
  2121142,
  634697,
  634697,
  634697,
  583623,
  1403937],
 2440: [1076643,
  1484762,
  1996251,
  262104,
  262104,
  132962,
  244857,
  1989172,
  1943248,
  109773],
 2445: [10956, 718143, 10956, 1468726],
 2466: [1882933,
  1882933,
  1882933,
  1882933,
  1882933,
  1882933,
  1583829,
  1660483,
  881530,
  1018511],
 2475: [1036762, 2012044, 424107],
 2478: [634697,
  634697,
  2121142,
  1803498,
  2121142,
  634697,
  634697,
  634697,
  583623,
  1403937],
 2484: [1044477, 1382259, 1151951, 537931],
 2489: [879873,
  1785953,
  1636026,
  959920,
  1319364,
  2080651,
  2210601,
  1048507,
  2210601,
  160373],
 2491: [634697,
  634697,
  634697,
  634697,
  2121142,
  2121142,
  1803498,
  634697,
  634697,
  583623],
 2496: [732142,
  1184568,
  1923463,
  1400773,
  2105961,
  904681,
  1884613,
  1445747,
  1665176,
  1867245],
 2501: [1767260,
  975590,
  707236,
  1105101,
  1133193,
  1332385,
  1332385,
  665311,
  465181,
  465181],
 2508: [1923463, 1184568, 1400773, 2105961, 904681, 1884613, 1445747, 1665176],
 2510: [1854498, 186703, 1150434, 1854498, 1150434, 1854498, 861260],
 2512: [771160,
  771160,
  771160,
  771160,
  1533664,
  686840,
  1425022,
  1425022,
  439201,
  439201],
 2603: [642236,
  855239,
  855239,
  82974,
  139255,
  139255,
  2093871,
  2093871,
  9061,
  9061],
 2608: [1097319,
  561949,
  2200767,
  312940,
  214904,
  1892900,
  894277,
  1831245,
  1214324,
  1287220],
 2653: [1132771,
  723954,
  723954,
  1610324,
  1205289,
  872680,
  1205289,
  1610324,
  1737635,
  2057117],
 2660: [762918,
  1027244,
  1705312,
  1130834,
  2020757,
  727552,
  944985,
  545687,
  15672,
  1844215],
 2669: [2232637,
  1700959,
  298769,
  1970612,
  1921922,
  1483790,
  1136960,
  850484,
  850484,
  2233825],
 2680: [807724,
  836790,
  2041051,
  2093788,
  2041051,
  74905,
  74905,
  276679,
  276679,
  2041051],
 2702: [1961854,
  1818138,
  1380066,
  1931034,
  1549484,
  1549484,
  1818138,
  575704,
  105468,
  1961854],
 2715: [1800653,
  1800653,
  1226345,
  2028485,
  967954,
  967954,
  1463530,
  202941,
  1487113,
  1487113],
 2727: [2166967, 816791, 505660, 1213211, 2203164],
 2805: [1817785, 706529, 1318024, 1158156],
 2809: [1688084, 1688084, 1499585, 774509, 2711, 1459283],
 2833: [634697,
  634697,
  2121142,
  1803498,
  2121142,
  634697,
  634697,
  634697,
  583623,
  1403937],
 2876: [786658, 2188250, 831663, 652855, 1428248, 34612, 1817476],
 2920: [1009015,
  106283,
  1549484,
  543815,
  792740,
  437748,
  836152,
  575704,
  1961854,
  1818138],
 2925: [679388, 1830194, 1804499, 969300, 1542364, 595128, 1520330, 1804499],
 2959: [1009015,
  871118,
  775961,
  719960,
  1549484,
  543815,
  437748,
  1380066,
  1731731,
  341804],
 2971: [117469,
  2159613,
  2159613,
  1131340,
  117469,
  1675881,
  543315,
  275891,
  1843413,
  275891],
 2988: [1931034,
  1549484,
  1818138,
  1380066,
  1404440,
  1813172,
  341804,
  871118,
  1549484,
  105468],
 3003: [1216272,
  1363281,
  914933,
  914933,
  1363281,
  914933,
  855469,
  1325415,
  1433280,
  855469],
 3005: [1699369,
  1928020,
  1699369,
  553802,
  1541090,
  1646604,
  1928020,
  2032579,
  2001981,
  1143697],
 3022: [634697,
  634697,
  2121142,
  2121142,
  1803498,
  634697,
  634697,
  634697,
  583623,
  1403937],
 3033: [2093788,
  276679,
  2041051,
  74905,
  276679,
  2041051,
  2041051,
  276679,
  197017,
  1035849],
 3045: [871118,
  1931034,
  1549484,
  2064555,
  105468,
  1961854,
  1931034,
  1549484,
  695606,
  1380066],
 3058: [1066396, 437838, 89356, 230786, 250742, 346621],
 3071: [1728894, 1728894, 1728894, 944235],
 3084: [634697,
  634697,
  634697,
  2121142,
  2121142,
  1803498,
  634697,
  634697,
  583623,
  1403937],
 3107: [975200,
  260823,
  1118916,
  500076,
  493865,
  493865,
  1388587,
  1388587,
  2276807,
  2276807],
 3131: [346836,
  2080651,
  2210601,
  1048507,
  2210601,
  879873,
  160373,
  863468,
  1785953,
  1319364],
 3136: [1142390,
  1915169,
  1279651,
  2257343,
  1250359,
  240248,
  240248,
  240248,
  240248,
  240248],
 3138: [788368, 1120304, 192531, 1317122, 912867],
 3161: [1690306, 19874, 2218177, 881810, 1089125, 1417500],
 3202: [20417, 2192887, 702173, 1911033, 455511],
 3220: [2149247, 1584983, 225939],
 3275: [1103477, 300409, 2208363],
 3285: [60133,
  1185432,
  1584983,
  300409,
  1633435,
  1052291,
  1497736,
  1639766,
  689387,
  1335921],
 3311: [1823461, 1282812, 1166535, 1166535, 1166535],
 3317: [1844215,
  944985,
  545687,
  15672,
  1557163,
  1148133,
  1651308,
  2132260,
  836843,
  1308603],
 3355: [1210071, 1498337, 1498337, 455477, 949176, 2080259, 174957, 2070506],
 3356: [2093115,
  1272319,
  1568939,
  1243085,
  1663741,
  818373,
  818373,
  1563398,
  1563398,
  9866],
 3389: [1767249, 711735, 961263, 961263, 1955247],
 3446: [612681,
  874661,
  1982609,
  1982609,
  207078,
  1244731,
  2261038,
  2261038,
  82643,
  207078],
 3458: [478445,
  2082280,
  367985,
  332262,
  332262,
  2116571,
  1659716,
  418739,
  1361338,
  344367],
 3466: [634697,
  634697,
  2121142,
  1803498,
  2121142,
  634697,
  634697,
  634697,
  583623,
  1403937],
 3484: [634697,
  2121142,
  2121142,
  1803498,
  634697,
  634697,
  583623,
  1403937,
  722448,
  722448],
 3506: [937461,
  1148099,
  2117420,
  2117420,
  1053991,
  2227500,
  2227500,
  1053991,
  1206608,
  1053991],
 3513: [1533216, 1533216, 1676090],
 3648: [634697,
  634697,
  2121142,
  1803498,
  2121142,
  634697,
  634697,
  583623,
  1403937,
  722448],
 3649: [2210601,
  160373,
  863468,
  346836,
  1319364,
  2080651,
  2210601,
  879873,
  1785953,
  959920],
 3674: [2056759,
  761040,
  408436,
  408436,
  497653,
  497653,
  497653,
  17757,
  427563,
  427563],
 3780: [1855763,
  408545,
  1664187,
  1664187,
  1664187,
  1979001,
  1979001,
  1193075,
  740198,
  1574030],
 3826: [1644657,
  1582449,
  2210893,
  896181,
  1533073,
  1417760,
  1533073,
  1533073,
  1533073,
  1157101],
 3870: [1724275,
  262349,
  2280867,
  91738,
  1528117,
  2070506,
  2073659,
  166584,
  166584,
  1238072],
 3880: [1216857,
  1658359,
  1658359,
  1324311,
  7064,
  7064,
  1729669,
  1658359,
  1729669,
  1729669],
 3909: [1476466,
  961528,
  194848,
  1815855,
  832818,
  373718,
  927460,
  1996838,
  521558,
  521558],
 3940: [1907066,
  268043,
  1907066,
  1639506,
  766371,
  1994413,
  766371,
  1639506,
  1977919,
  1402182],
 3992: [634697,
  634697,
  634697,
  2121142,
  1803498,
  634697,
  634697,
  634697,
  583623,
  1403937],
 4004: [1318109,
  771160,
  771160,
  771160,
  1533664,
  686840,
  1425022,
  1425022,
  439201,
  439201],
 4028: [2113512,
  554007,
  504915,
  739896,
  739896,
  162887,
  124228,
  1674666,
  363195,
  739896],
 4059: [2058676,
  2058676,
  1414729,
  1414729,
  640056,
  701065,
  701065,
  404512,
  858856,
  163233],
 4063: [338977,
  1895815,
  74639,
  2235384,
  1184278,
  439774,
  780987,
  1224559,
  972490,
  668542],
 4107: [1998787, 1113176, 420643, 957327, 453880],
 4125: [942592,
  942592,
  942592,
  1166720,
  518146,
  1166720,
  770478,
  1220360,
  727702,
  474589],
 4151: [2121142,
  2121142,
  1803498,
  634697,
  634697,
  634697,
  583623,
  1403937,
  722448,
  722448],
 4172: [1294592, 1807974, 634384, 258745, 2223753, 509739],
 4249: [1009015,
  341804,
  437748,
  1549484,
  2064555,
  1961854,
  775961,
  575704,
  1731731,
  1818138],
 4279: [1861795,
  785084,
  785084,
  1861795,
  921345,
  554421,
  921345,
  476380,
  476380,
  1418568],
 4297: [522230,
  1193149,
  2070933,
  1992333,
  1700016,
  2122825,
  1970963,
  1164647,
  112961,
  2207077],
 4307: [106283,
  719960,
  836152,
  543815,
  1731731,
  1475714,
  341804,
  1818138,
  575704,
  1404440],
 4316: [1119603,
  1677371,
  1142339,
  1119603,
  1949117,
  1119603,
  1523817,
  300409,
  1886435,
  193677],
 4322: [2070049, 879064, 241827],
 4329: [638251,
  213964,
  738205,
  1386161,
  2159613,
  1589925,
  448554,
  1940672,
  1589925,
  1030883],
 4346: [184181, 1728894, 1728894, 1728894, 944235],
 4368: [398800, 503422, 503422, 2097665, 320099, 345984, 176506, 1695388],
 4401: [1408699, 18961, 461671, 922575, 1946296, 1132974, 1413688],
 4413: [647704,
  647704,
  647704,
  647704,
  372307,
  986942,
  342850,
  1230168,
  482220,
  746432],
 4421: [634697,
  634697,
  634697,
  634697,
  2121142,
  2121142,
  634697,
  634697,
  583623,
  1403937],
 4429: [2180432,
  1318109,
  771160,
  771160,
  1533664,
  686840,
  1425022,
  1425022,
  439201,
  439201],
 4481: [1182381,
  1182381,
  1394044,
  1315266,
  469286,
  1877654,
  124546,
  74515,
  427214,
  1164744],
 4488: [2184538, 224444, 1600514, 1600514],
 4499: [2149202, 2149202, 269430],
 4539: [526122, 1208789, 526122],
 4570: [917183, 1757095, 1053278, 1048387, 571426, 2141395, 28431],
 4594: [398123,
  5461,
  752465,
  864010,
  844756,
  1242379,
  1526654,
  1005411,
  1472320,
  1384994],
 4608: [766268, 530970, 1800102, 613264, 613264, 38515, 530970, 613264],
 4648: [103173,
  1186947,
  890786,
  1362430,
  1362430,
  123751,
  75156,
  75156,
  795757,
  1944872],
 4711: [2210601,
  2080651,
  1636026,
  1319364,
  1048507,
  2210601,
  879873,
  1785953,
  863468,
  346836],
 4712: [445119,
  307286,
  307286,
  1789181,
  1514375,
  941216,
  941216,
  677892,
  374770,
  2201852],
 4734: [387470,
  1472521,
  1472521,
  26125,
  550593,
  1669592,
  550593,
  1472521,
  1472521,
  767560],
 4762: [762477, 4482, 1421153, 1958429],
 4775: [2088717, 2088717, 393310, 668542, 1465363, 1465363],
 4803: [1705312,
  1130834,
  2020757,
  727552,
  944985,
  1844215,
  545687,
  15672,
  1557163,
  1651308],
 4841: [793601, 2278739, 46797, 1013223, 209370, 209370, 209370, 859902],
 4885: [1710195, 1710195, 1329333, 1279651],
 4902: [2001680, 74639, 2001680, 74639],
 4935: [408436, 971385, 971385, 252884, 1675322, 1623528],
 4957: [1498725,
  79810,
  2200356,
  31523,
  2145988,
  1498725,
  2130935,
  794005,
  404083,
  615949],
 4970: [634697,
  1803498,
  2121142,
  2121142,
  634697,
  634697,
  634697,
  1403937,
  722448,
  722448],
 4972: [207934, 1288649, 1380159, 1288649, 1288649],
 4975: [206940, 430870, 1972848, 1482870],
 4976: [1426761,
  1658209,
  232881,
  568852,
  577761,
  654647,
  816399,
  1658209,
  1658209,
  577761],
 4987: [1982726, 117469, 117469],
 4999: [432019,

In [77]:
# build a dictionary with user_id, the user history, and the target item (which comes from the interactions of the last week)
rows = []

for _, row in after_cutoff.iterrows():
    user = row['user_id']
    target_item = row['item_id']
    
    if user not in history_dict:
        continue
        
    history = history_dict[user]
    
    rows.append({
        "user_id": user,
        "history": history,
        "target_id": target_item
    })

In [78]:
# convert it to dataframe
final_df = pd.DataFrame(rows)

In [79]:
final_df.head()

   user_id                                            history  target_id
0   954576  [1750066, 1017768, 1017768, 1017768, 29790, 49...    1594762
1  1577924  [459638, 5188, 459638, 1219428, 459638, 121942...    1974378
2  1263143  [1519786, 712458, 1090714, 1127606, 1127606, 2...    1341080
3  1434291  [1951040, 1951040, 1951040, 1951040, 1305888, ...    1021192
4  1789388  [797506, 1333362, 1333362, 1287732, 758916, 75...    1788653

In [ ]:
len(final_df)

367818

In [ ]:
# check number of unique users
len(set(final_df['user_id']))

94571

In [81]:
# check that all histories have at least 3 items
final_df['history'].apply(len).min()

3

#### Convert history item ids to text

Here we need to convert the history (and also target_id) into informative text so that, in the future, when we embed the history, the embeddings will be informative enough for the LLM. Since we do not have a title for each job item, we can create one based on the industry and discipline, maybe also include the country. The issue is that the dataset uses anonymized IDs for the industry and discipline of each job posting. One solution here would be that we create synthetic mapping from the industry and discipline IDs to their name. There are 23 industry IDs, and 23 discipline IDs.

#### Add synthetic gender and age

In [96]:
# we want to keep the dataset balanced, so we add randomly 50% males and 50% females

np.random.seed(42)

unique_users = final_df['user_id'].unique()

gender_map = {user: np.random.choice(['Male', 'Female'])
              for user in unique_users}

final_df['gender'] = final_df['user_id'].map(gender_map)

In [ ]:
# check the distribution
final_df["gender"].value_counts(normalize=True)

gender
Male      0.501278
Female    0.498722
Name: proportion, dtype: float64

Now, to add the synthetic age, we can take advantage that we know the total experience years of each user. This is indicative of the age range.

In [105]:
# first add the experience years to final_df so we merge later easily
users = users.rename(mapper={'id':'user_id'}, axis='columns')
final_df = final_df.merge(
    users[['user_id','experience_years_experience']],
    on='user_id',
    how='left'
)

We have this mapping from the dataset documentation:  
  
0 = unknown.  
1 = less than 1 year  
2 = 1 - 3 years  
3 = 3 - 5 years  
4 = 5 - 10 years  
5 = 10 - 20 years  
6 = more than 20 years  
  
We remove the users with unknown experience years.   
  
We can assign the age range as follows:  
1 = 20 - 22 years old  
2 = 23 - 25 years old  
3 = 26 - 30 years old  
4 = 31 - 40 years old  
5 = 41 - 54 years old  
6 = 55+ years old

In [113]:
# first remove the users with unknow experience
final_df = final_df[final_df['experience_years_experience'] != 0]

# now create age map and age_range column
age_map = {1: '20-22', 2:'23-25', 3:'26-30', 4:'31-40', 5:'41-54', 6:'55+'}
final_df['age_range'] = final_df['experience_years_experience'].map(age_map)

In [116]:
# remove the experience years since we do not need them anymore
final_df = final_df[['user_id', 'history', 'target_id', 'gender', 'age_range']]

In [117]:
final_df.head()

,user_id,history,target_id,gender,age_range
0,954576,"[1750066, 1017768, 1017768, 1017768, 29790, 49...",1594762,Male,23-25
1,1577924,"[459638, 5188, 459638, 1219428, 459638, 121942...",1974378,Female,55+
2,1263143,"[1519786, 712458, 1090714, 1127606, 1127606, 2...",1341080,Male,41-54
3,1434291,"[1951040, 1951040, 1951040, 1951040, 1305888, ...",1021192,Male,31-40
4,1789388,"[797506, 1333362, 1333362, 1287732, 758916, 75...",1788653,Male,41-54